-- PARTIE 1
-- Question 1
SELECT NOMPILOTE,
    ADRESSE
FROM PILOTE;
-- Question 2
SELECT DISTINCT VILLEDEP
FROM VOL;
-- Question 3
SELECT NUMVOL,
    VILLEDEP,
    VILLEARR,
    HEUREDEP,
    HEUREARR
FROM VOL
WHERE VILLEDEP = 'Paris'
    AND HEUREDEP BETWEEN '14:00' AND '16:00';
-- Question 4
SELECT *
FROM AVION
WHERE NOMAVION LIKE 'Airbus%';
-- Question 5
SELECT *
FROM PILOTE
WHERE NOMPILOTE LIKE '_i%';
-- Question 6
SELECT *
FROM AVION
WHERE CAPACITE BETWEEN 200 AND 300;
-- Question 7
SELECT NOMAVION,
    NUMAVION,
    LOCALISATION
FROM AVION
WHERE CAPACITE > 200
    AND LOCALISATION <> 'Nice'
ORDER BY NUMAVION DESC;
-- Question 8
SELECT DISTINCT P.NOMPILOTE
FROM PILOTE P
    JOIN VOL V ON P.NUMPILOTE = V.NUMPILOTE
WHERE V.VILLEDEP = 'Paris';
-- Question 9
SELECT DISTINCT P.NOMPILOTE
FROM PILOTE P
    JOIN AVION A ON P.ADRESSE = A.LOCALISATION
WHERE A.NOMAVION LIKE 'Airbus%';
-- Question 10
SELECT DISTINCT P.NOMPILOTE
FROM PILOTE P
    JOIN VOL V ON P.NUMPILOTE = V.NUMPILOTE
WHERE V.NUMAVION IN (
        SELECT NUMAVION
        FROM VOL
        WHERE NUMPILOTE = 2
    );
-- Question 11
SELECT A.NUMAVION,
    A.NOMAVION
FROM AVION A
    JOIN VOL V ON A.LOCALISATION = V.VILLEDEP
WHERE A.CAPACITE BETWEEN 200 AND 300
    AND V.NUMVOL = 'USA050';
-- Question 12
SELECT *
FROM AVION A
WHERE CAPACITE > ALL (
        SELECT CAPACITE
        FROM AVION
        WHERE LOCALISATION = 'Nice'
    );
-- Question 13
SELECT *
FROM AVION A
WHERE CAPACITE > ANY (
        SELECT CAPACITE
        FROM AVION
        WHERE LOCALISATION = 'Nice'
    );
-- Question 14
WITH ArrivalsByAder AS (
    SELECT DISTINCT VILLEARR
    FROM VOL
    WHERE NUMPILOTE = 1
)
SELECT DISTINCT P.NOMPILOTE
FROM PILOTE P
    JOIN AVION A ON P.ADRESSE = A.LOCALISATION
    JOIN VOL V ON P.NUMPILOTE = V.NUMPILOTE
    JOIN ArrivalsByAder AA ON V.VILLEDEP = AA.VILLEARR
WHERE A.NOMAVION LIKE 'Airbus%';
-- PARTIE 2
-- Question 1
SELECT COUNT(DISTINCT NUMPILOTE)
FROM VOL;
-- Question 2
SELECT NUMAVION
FROM AVION A
WHERE CAPACITE >= (
        SELECT AVG(CAPACITE)
        FROM AVION
        WHERE LOCALISATION = A.LOCALISATION
    );
-- Question 3
SELECT NUMAVION,
    NOMAVION
FROM AVION
WHERE CAPACITE * 1.1 > 250;
-- Question 4
SELECT *
FROM PILOTE
WHERE SOUNDEX(NOMPILOTE) = SOUNDEX('Blériaud');
-- Question 5
SELECT *
FROM AVION
WHERE CAPACITE > 1.1 * (
        SELECT AVG(CAPACITE)
        FROM AVION
    );
-- Question 6
SELECT NUMPILOTE,
    COUNT(*) AS nb_vols
FROM VOL
GROUP BY NUMPILOTE;